spring:
  datasource:
    url: jdbc:mysql://localhost:3306/activitidemo?serverTimezone=GMT&useSSL=false&characterEncoding=UTF-8&nullCatalogMeansCurrent=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
